fix: atualiza footer com mapa do site
osfenix/fenix-website pull request #19
Opened 2022-01-08 21:21 UTC by adviuriaraujo

e refatora função do botão voltar na tela Enviado.

2022-01-08 21:58 UTC, mattheusz commented
De uma forma geral, está tudo OK!
Apenas uma ressalva: ao estar na página inicial, ao clicar tanto em _O Instituto_ e _Causas_, poderia ter o mesmo comportamento que acontece ao clicar acessar essas seções pelo menu: rolar a página ao invés par aa seção, ao invés de recarregar a página.

2022-01-08 22:29 UTC, mattheusz requested changes
No mapa do site, alterar o link para a seção **instituto** e para a seção **causas**.
No mais, tudo OK!

2022-01-08 22:29 UTC, mattheusz commented on src/index.html
> +                            <a class="footer__right-box__grid__item" href="index.html#causas">Causas</a>
trocar `index.html#causas` para apenas `#causas`

2022-01-08 22:29 UTC, mattheusz commented on src/index.html
> +                            <a class="footer__right-box__grid__item" href="index.html#instituto">O Instituto</a>
trocar `index.html#instituto` para apenas `#instituto`

2022-01-09 10:50 UTC, adviuriaraujo commented on src/index.html
> +                            <a class="footer__right-box__grid__item" href="index.html#instituto">O Instituto</a>
trocado no novo commit.

2022-01-09 10:57 UTC, adviuriaraujo commented
Troquei as imagens nos cards das causas pelas fotos. Testei colocar no formato do protótipo, mas a princípio as fotos ficariam muito grandes na tela comparando com os outros elementos do site. Como os cards que você fez ficaram bons tanto no desktop quanto no mobile, acho melhor mantê-los.

Coloquei o card para ter display flex por padrão, pois estava ficando com um espaço entre a imagem e o body.

2022-01-09 14:43 UTC, mattheusz commented
Tudo certo! Ficou muito bom! Aprovado.

2022-01-09 19:22 UTC, merged